name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer Cython==0.29.33
        sudo apt-get update
        sudo apt-get install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        sudo apt-get install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
        sudo apt-get install -y android-tools-adb android-tools-fastboot
    
    - name: Setup Android SDK and Build Tools
      run: |
        BUILD_TOOLS_VERSION="33.0.0"
        TEMP_DIR="/tmp/android_sdk"
        
        # Create main SDK directory
        mkdir -p "${ANDROID_HOME}"
        
        # Download and extract command line tools
        mkdir -p "${TEMP_DIR}"
        cd "${TEMP_DIR}"
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        
        # Create the expected directory structure
        mkdir -p "${ANDROID_HOME}/cmdline-tools/latest"
        mv cmdline-tools/* "${ANDROID_HOME}/cmdline-tools/latest/"
        
        # Set executable permissions
        chmod +x "${ANDROID_HOME}/cmdline-tools/latest/bin/"*
        
        # Accept licenses
        yes | "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --sdk_root="${ANDROID_HOME}" --licenses
        
        # Install required components
        "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --sdk_root="${ANDROID_HOME}" \
            "platform-tools" \
            "build-tools;${BUILD_TOOLS_VERSION}" \
            "platforms;android-33"
        
        # Set permissions
        sudo chown -R $USER:$USER "${ANDROID_HOME}"
        
        # Verify installations
        echo "Verifying installations..."
        /bin/ls -la "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager"
        /bin/ls -la "${ANDROID_HOME}/platform-tools/adb" || echo "adb not found"
        /bin/ls -la "${ANDROID_HOME}/build-tools/${BUILD_TOOLS_VERSION}/aidl" || echo "aidl not found"
        
        # Clean up
        rm -rf "${TEMP_DIR}"
    
    - name: Set up buildozer
      run: |
        echo '[app]' > buildozer.spec
        echo 'title = Yoga Timer' >> buildozer.spec
        echo 'package.name = yogatimer' >> buildozer.spec
        echo 'package.domain = org.example' >> buildozer.spec
        echo 'source.dir = .' >> buildozer.spec
        echo 'source.include_exts = py,wav' >> buildozer.spec
        echo 'version = 0.1' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'requirements = python3,kivy,plyer,android,Cython==0.29.33' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE' >> buildozer.spec
        echo 'p4a.bootstrap = sdl2' >> buildozer.spec
        echo 'android.archs = arm64-v8a' >> buildozer.spec
        echo 'android.api = 33' >> buildozer.spec
        echo 'android.minapi = 21' >> buildozer.spec
        echo 'android.ndk = 25b' >> buildozer.spec
        echo 'android.accept_sdk_license = True' >> buildozer.spec
        echo "android.sdk_path = ${ANDROID_HOME}" >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'android.presplash_color = #FFFFFF' >> buildozer.spec
        echo 'android.orientation = portrait' >> buildozer.spec
        echo '' >> buildozer.spec
        echo '[buildozer]' >> buildozer.spec
        echo 'log_level = 2' >> buildozer.spec
        echo 'warn_on_root = 1' >> buildozer.spec
    
    - name: Build with Buildozer
      run: |
        export PATH="${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:$PATH"
        echo "ANDROID_HOME: ${ANDROID_HOME}"
        echo "PATH: $PATH"
        echo "Current directory: $(/bin/pwd)"
        echo "Android SDK contents:"
        /bin/ls -R "${ANDROID_HOME}"
        buildozer android debug -v
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: bin/*.apk
