name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer Cython==0.29.33
        sudo apt-get update
        sudo apt-get install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        sudo apt-get install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
        sudo apt-get install -y android-tools-adb android-tools-fastboot
    
    - name: Setup Android SDK and Build Tools
      run: |
        # Set up Android SDK
        ANDROID_SDK_ROOT="/usr/local/lib/android/sdk"
        CMDLINE_TOOLS_ROOT="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin"
        BUILD_TOOLS_VERSION="33.0.0"
        
        # Download and install command line tools
        sudo wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        sudo mkdir -p ${ANDROID_SDK_ROOT}/cmdline-tools
        sudo unzip -q commandlinetools-linux-9477386_latest.zip -d ${ANDROID_SDK_ROOT}/cmdline-tools
        sudo mv ${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools ${ANDROID_SDK_ROOT}/cmdline-tools/latest
        
        # Set up environment variables
        export ANDROID_HOME=${ANDROID_SDK_ROOT}
        export PATH=${PATH}:${CMDLINE_TOOLS_ROOT}
        
        # Accept licenses and install components
        yes | sudo ${CMDLINE_TOOLS_ROOT}/sdkmanager --licenses
        sudo ${CMDLINE_TOOLS_ROOT}/sdkmanager --install "build-tools;${BUILD_TOOLS_VERSION}" "platforms;android-33" "platform-tools"
        
        # Set up buildozer paths
        mkdir -p $HOME/.buildozer/android/platform/android-sdk
        sudo ln -s ${ANDROID_SDK_ROOT}/build-tools/${BUILD_TOOLS_VERSION} $HOME/.buildozer/android/platform/android-sdk/build-tools
        sudo ln -s ${ANDROID_SDK_ROOT}/platforms $HOME/.buildozer/android/platform/android-sdk/platforms
        sudo ln -s ${ANDROID_SDK_ROOT}/platform-tools $HOME/.buildozer/android/platform/android-sdk/platform-tools
        
        # Verify aidl exists
        ls -la ${ANDROID_SDK_ROOT}/build-tools/${BUILD_TOOLS_VERSION}/aidl
        ls -la $HOME/.buildozer/android/platform/android-sdk/build-tools/${BUILD_TOOLS_VERSION}/aidl
        
        # Set permissions
        sudo chown -R $USER:$USER $HOME/.buildozer
    
    - name: Set up buildozer
      run: |
        echo '[app]' > buildozer.spec
        echo 'title = Yoga Timer' >> buildozer.spec
        echo 'package.name = yogatimer' >> buildozer.spec
        echo 'package.domain = org.example' >> buildozer.spec
        echo 'source.dir = .' >> buildozer.spec
        echo 'source.include_exts = py,wav' >> buildozer.spec
        echo 'version = 0.1' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'requirements = python3,kivy,plyer,android,Cython==0.29.33' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE' >> buildozer.spec
        echo 'p4a.bootstrap = sdl2' >> buildozer.spec
        echo 'android.archs = arm64-v8a' >> buildozer.spec
        echo 'android.api = 33' >> buildozer.spec
        echo 'android.minapi = 21' >> buildozer.spec
        echo 'android.ndk = 25b' >> buildozer.spec
        echo 'android.accept_sdk_license = True' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'android.presplash_color = #FFFFFF' >> buildozer.spec
        echo 'android.orientation = portrait' >> buildozer.spec
        echo '' >> buildozer.spec
        echo '[buildozer]' >> buildozer.spec
        echo 'log_level = 2' >> buildozer.spec
        echo 'warn_on_root = 1' >> buildozer.spec
    
    - name: Build with Buildozer
      env:
        BUILDOZER_ANDROID_SDK: $HOME/.buildozer/android/platform/android-sdk
      run: |
        buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: bin/*.apk
