name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      PATH: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java 11
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        java -version

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        # Update package list
        sudo apt-get update
        
        # Install essential packages
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-11-jdk \
          python3-pip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          virtualenv \
          build-essential \
          ccache
          
        # Create symbolic link for git in /usr/bin if it doesn't exist
        sudo ln -sf $(which git) /usr/bin/git
        
        # Verify git installation
        which git
        git --version
        
        # Install Python packages
        python -m pip install --upgrade pip
        pip install --upgrade Cython==0.29.33 buildozer==1.5.0
        
        # Verify buildozer installation
        buildozer --version

    - name: Setup Android SDK
      run: |
        mkdir -p ${ANDROID_HOME}
        
        # Download and extract command line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        
        # Create proper directory structure
        mkdir -p ${ANDROID_HOME}/cmdline-tools/latest
        mv cmdline-tools/* ${ANDROID_HOME}/cmdline-tools/latest/
        rm -rf cmdline-tools
        
        # Create tools directory structure
        mkdir -p ${ANDROID_HOME}/tools/bin
        ln -s ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager ${ANDROID_HOME}/tools/bin/sdkmanager
        
        # Set permissions
        chmod +x ${ANDROID_HOME}/cmdline-tools/latest/bin/*
        sudo chown -R $USER:$USER ${ANDROID_HOME}
        
        # Install SDK components
        yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_HOME} --licenses
        ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_HOME} \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.0"

    - name: Setup buildozer.spec
      run: |
        cat > buildozer.spec << EOF
[app]
title = Yoga Timer
package.name = yogatimer
package.domain = org.example
source.dir = .
source.include_exts = py,wav
version = 0.1

requirements = python3,kivy,plyer,android,Cython==0.29.33

android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE
p4a.bootstrap = sdl2
android.archs = arm64-v8a
android.api = 33
android.minapi = 21
android.ndk = 25b
android.accept_sdk_license = True
android.skip_update = True
android.sdk_path = ${ANDROID_HOME}

android.presplash_color = #FFFFFF
android.orientation = portrait

[buildozer]
log_level = 2
warn_on_root = 1
EOF

    - name: Verify environment
      run: |
        echo "=== System Path ==="
        echo $PATH
        
        echo "=== Git Version and Location ==="
        which git
        git --version
        
        echo "=== Android SDK Location ==="
        echo $ANDROID_HOME
        ls -la $ANDROID_HOME
        
        echo "=== Java Version ==="
        java -version
        echo $JAVA_HOME
        
        echo "=== Python Version ==="
        python --version
        pip list
        
        echo "=== Buildozer Version ==="
        buildozer --version

    - name: Build APK
      run: |
        export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:$PATH"
        buildozer android debug -v

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: bin/*.apk
