name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo mkdir -p bin .buildozer
          sudo chown -R $(id -u):$(id -g) .
          sudo chmod -R 755 .
          touch buildozer.spec
          sudo chown $(id -u):$(id -g) buildozer.spec
          sudo chmod 644 buildozer.spec
          
          # Verify permissions
          ls -la
          ls -la buildozer.spec

      - name: Create buildozer.spec
        run: |
          cat > buildozer.spec << 'SPEC'
[app]
title = Yoga Timer
package.name = yogatimer
package.domain = org.example
source.dir = .
source.include_exts = py,wav
version = 0.1

requirements = python3,kivy==2.2.1,plyer,android

android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE
p4a.bootstrap = sdl2
android.archs = arm64-v8a
android.api = 33
android.minapi = 21
android.ndk = r25b
android.accept_sdk_license = True
android.gradle_dependencies = androidx.core:core:1.6.0
android.enable_androidx = True

android.presplash_color = #FFFFFF
android.orientation = portrait

[buildozer]
log_level = 2
warn_on_root = 1
SPEC

      - name: Build with Docker
        uses: docker://kivy/buildozer:latest
        with:
          args: android debug

      - name: Fix permissions
        if: always()
        run: sudo chown -R $(id -u):$(id -g) .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: app
          path: bin/*.apk
          if-no-files-found: error

      - name: Upload logs on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-logs
          path: |
            .buildozer/android/build.log
            .buildozer/android/platform/*/build/*.log
