name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          mkdir -p bin .buildozer
          sudo chown -R 1000:1000 .
          sudo chmod -R 755 .

      - name: Create buildozer.spec
        run: |
          echo "[app]" > buildozer.spec
          echo "title = Yoga Timer" >> buildozer.spec
          echo "package.name = yogatimer" >> buildozer.spec
          echo "package.domain = org.example" >> buildozer.spec
          echo "source.dir = ." >> buildozer.spec
          echo "source.include_exts = py,wav" >> buildozer.spec
          echo "version = 0.1" >> buildozer.spec
          echo "" >> buildozer.spec
          echo "requirements = python3,kivy==2.2.1,plyer,android" >> buildozer.spec
          echo "" >> buildozer.spec
          echo "android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE" >> buildozer.spec
          echo "p4a.bootstrap = sdl2" >> buildozer.spec
          echo "android.archs = arm64-v8a" >> buildozer.spec
          echo "android.api = 33" >> buildozer.spec
          echo "android.minapi = 21" >> buildozer.spec
          echo "android.ndk = r25b" >> buildozer.spec
          echo "android.accept_sdk_license = True" >> buildozer.spec
          echo "android.gradle_dependencies = androidx.core:core:1.6.0" >> buildozer.spec
          echo "android.enable_androidx = True" >> buildozer.spec
          echo "" >> buildozer.spec
          echo "android.presplash_color = #FFFFFF" >> buildozer.spec
          echo "android.orientation = portrait" >> buildozer.spec
          echo "" >> buildozer.spec
          echo "[buildozer]" >> buildozer.spec
          echo "log_level = 2" >> buildozer.spec
          echo "warn_on_root = 1" >> buildozer.spec

      - name: Build with Docker
        uses: docker://kivy/buildozer:latest
        with:
          args: android debug

      - name: Fix permissions
        if: always()
        run: sudo chown -R $USER:$USER .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: app
          path: bin/*.apk
          if-no-files-found: error

      - name: Upload logs on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-logs
          path: |
            .buildozer/android/build.log
            .buildozer/android/platform/*/build/*.log
