name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java 11
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        java -version
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer Cython==0.29.33
        sudo apt-get install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        sudo apt-get install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
        sudo apt-get install -y android-tools-adb android-tools-fastboot
    
    - name: Setup Android SDK
      run: |
        # Set up Android SDK root
        mkdir -p ${ANDROID_HOME}
        
        # Download the command-line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        
        # Create the expected directory structure
        mkdir -p ${ANDROID_HOME}/cmdline-tools/latest
        mv cmdline-tools/* ${ANDROID_HOME}/cmdline-tools/latest/
        
        # Set executable permissions
        chmod +x ${ANDROID_HOME}/cmdline-tools/latest/bin/*
        
        # Create tools directory structure (for buildozer compatibility)
        mkdir -p ${ANDROID_HOME}/tools/bin
        ln -s ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager ${ANDROID_HOME}/tools/bin/sdkmanager
        
        # Accept licenses and install required components
        export PATH=${ANDROID_HOME}/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --licenses --sdk_root=${ANDROID_HOME}
        sdkmanager --sdk_root=${ANDROID_HOME} \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.0" \
            "extras;android;m2repository" \
            "extras;google;m2repository"
        
        # Verify installation
        ls -la ${ANDROID_HOME}/tools/bin/sdkmanager
        ls -la ${ANDROID_HOME}/platform-tools/
        ls -la ${ANDROID_HOME}/build-tools/33.0.0/
    
    - name: Set up buildozer
      run: |
        echo '[app]' > buildozer.spec
        echo 'title = Yoga Timer' >> buildozer.spec
        echo 'package.name = yogatimer' >> buildozer.spec
        echo 'package.domain = org.example' >> buildozer.spec
        echo 'source.dir = .' >> buildozer.spec
        echo 'source.include_exts = py,wav' >> buildozer.spec
        echo 'version = 0.1' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'requirements = python3,kivy,plyer,android,Cython==0.29.33' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE' >> buildozer.spec
        echo 'p4a.bootstrap = sdl2' >> buildozer.spec
        echo 'android.archs = arm64-v8a' >> buildozer.spec
        echo 'android.api = 33' >> buildozer.spec
        echo 'android.minapi = 21' >> buildozer.spec
        echo 'android.ndk = 25b' >> buildozer.spec
        echo 'android.accept_sdk_license = True' >> buildozer.spec
        echo "android.sdk_path = ${ANDROID_HOME}" >> buildozer.spec
        echo 'android.skip_update = True' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'android.presplash_color = #FFFFFF' >> buildozer.spec
        echo 'android.orientation = portrait' >> buildozer.spec
        echo '' >> buildozer.spec
        echo '[buildozer]' >> buildozer.spec
        echo 'log_level = 2' >> buildozer.spec
        echo 'warn_on_root = 1' >> buildozer.spec
    
    - name: Build with Buildozer
      env:
        PATH: ${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:${PATH}
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        
        echo "Java version:"
        java -version
        
        echo "ANDROID_HOME: ${ANDROID_HOME}"
        echo "JAVA_HOME: ${JAVA_HOME}"
        echo "PATH: $PATH"
        
        buildozer android debug -v
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: bin/*.apk
