name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer Cython==0.29.33
        sudo apt-get update
        sudo apt-get install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        sudo apt-get install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
        sudo apt-get install -y android-tools-adb android-tools-fastboot
    
    - name: Setup Android SDK and Build Tools
      run: |
        # Set up Android SDK
        BUILD_TOOLS_VERSION="33.0.0"
        ANDROID_HOME="$HOME/.buildozer/android/platform/android-sdk"
        TEMP_DIR="$HOME/temp_android_sdk"
        
        # Create directories
        mkdir -p ${ANDROID_HOME}/{tools,platforms,platform-tools,build-tools/${BUILD_TOOLS_VERSION}}
        mkdir -p ${TEMP_DIR}
        
        # Download and extract command line tools to temporary directory
        cd ${TEMP_DIR}
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        
        # Move tools to correct location
        rm -rf ${ANDROID_HOME}/tools
        mv cmdline-tools ${ANDROID_HOME}/tools
        
        # Set permissions
        sudo chown -R $USER:$USER ${ANDROID_HOME}
        chmod +x ${ANDROID_HOME}/tools/bin/*
        
        # Set environment variables
        export ANDROID_HOME=${ANDROID_HOME}
        export PATH=${PATH}:${ANDROID_HOME}/tools/bin
        
        # Verify sdkmanager exists
        if [ ! -f "${ANDROID_HOME}/tools/bin/sdkmanager" ]; then
            echo "sdkmanager not found!"
            exit 1
        fi
        
        # Accept licenses and install components
        yes | ${ANDROID_HOME}/tools/bin/sdkmanager --licenses || true
        ${ANDROID_HOME}/tools/bin/sdkmanager --update
        
        # Install required components
        ${ANDROID_HOME}/tools/bin/sdkmanager "platform-tools" "build-tools;${BUILD_TOOLS_VERSION}" "platforms;android-33"
        
        # Verify installations
        for file in "${ANDROID_HOME}/tools/bin/sdkmanager" "${ANDROID_HOME}/platform-tools/adb" "${ANDROID_HOME}/build-tools/${BUILD_TOOLS_VERSION}/aidl"; do
            if [ ! -f "$file" ]; then
                echo "Required file not found: $file"
                exit 1
            fi
            echo "Found: $file"
        done
        
        # Clean up
        cd $HOME
        rm -rf ${TEMP_DIR}
    
    - name: Set up buildozer
      run: |
        echo '[app]' > buildozer.spec
        echo 'title = Yoga Timer' >> buildozer.spec
        echo 'package.name = yogatimer' >> buildozer.spec
        echo 'package.domain = org.example' >> buildozer.spec
        echo 'source.dir = .' >> buildozer.spec
        echo 'source.include_exts = py,wav' >> buildozer.spec
        echo 'version = 0.1' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'requirements = python3,kivy,plyer,android,Cython==0.29.33' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE' >> buildozer.spec
        echo 'p4a.bootstrap = sdl2' >> buildozer.spec
        echo 'android.archs = arm64-v8a' >> buildozer.spec
        echo 'android.api = 33' >> buildozer.spec
        echo 'android.minapi = 21' >> buildozer.spec
        echo 'android.ndk = 25b' >> buildozer.spec
        echo 'android.accept_sdk_license = True' >> buildozer.spec
        echo "android.sdk_path = $HOME/.buildozer/android/platform/android-sdk" >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'android.presplash_color = #FFFFFF' >> buildozer.spec
        echo 'android.orientation = portrait' >> buildozer.spec
        echo '' >> buildozer.spec
        echo '[buildozer]' >> buildozer.spec
        echo 'log_level = 2' >> buildozer.spec
        echo 'warn_on_root = 1' >> buildozer.spec
    
    - name: Build with Buildozer
      env:
        ANDROID_HOME: $HOME/.buildozer/android/platform/android-sdk
        PATH: $PATH:$HOME/.buildozer/android/platform/android-sdk/tools/bin
      run: |
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "PATH: $PATH"
        echo "Current directory: $(pwd)"
        echo "Android SDK contents:"
        ls -R $ANDROID_HOME
        buildozer android debug -v
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: bin/*.apk
