name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
      ANDROID_NDK_HOME: /home/runner/.buildozer/android/platform/android-ndk-r25b
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java 11
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install and verify system dependencies
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          git \
          zip \
          unzip \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          virtualenv \
          build-essential \
          wget \
          sudo \
          nano \
          curl

        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade Cython==0.29.33
        python3 -m pip install --upgrade buildozer
        python3 -m pip install --upgrade python-for-android
        
        mkdir -p /home/runner/.buildozer
        sudo chown -R $USER:$USER /home/runner/.buildozer

    - name: Set up Android SDK and NDK
      run: |
        mkdir -p ${ANDROID_HOME}/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mv cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest
        rm commandlinetools-linux-9477386_latest.zip
        
        export PATH=${ANDROID_HOME}/cmdline-tools/latest/bin:$PATH
        
        mkdir -p ${ANDROID_HOME}/licenses
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ${ANDROID_HOME}/licenses/android-sdk-license
        
        yes | sdkmanager --licenses --sdk_root=${ANDROID_HOME}
        sdkmanager --sdk_root=${ANDROID_HOME} \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.0" \
          "ndk;25.1.8937393"

    - name: Create recipes directory
      run: |
        mkdir -p recipes/sdl2
        echo 'from pythonforandroid.recipe import BootstrapNDKRecipe
        
        class SDL2Recipe(BootstrapNDKRecipe):
            version = "2.28.3"
            url = "https://github.com/libsdl-org/SDL/archive/refs/tags/release-{version}.zip"
            depends = ["sdl2_image", "sdl2_mixer", "sdl2_ttf"]' > recipes/sdl2/__init__.py

    - name: Setup buildozer.spec
      run: |
        echo '[app]' > buildozer.spec
        echo 'title = Yoga Timer' >> buildozer.spec
        echo 'package.name = yogatimer' >> buildozer.spec
        echo 'package.domain = org.example' >> buildozer.spec
        echo 'source.dir = .' >> buildozer.spec
        echo 'source.include_exts = py,wav,toml' >> buildozer.spec
        echo 'version = 0.1' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'requirements = python3,kivy==2.2.1,plyer,android' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE' >> buildozer.spec
        echo 'p4a.bootstrap = sdl2' >> buildozer.spec
        echo 'android.archs = arm64-v8a' >> buildozer.spec
        echo 'android.api = 33' >> buildozer.spec
        echo 'android.minapi = 21' >> buildozer.spec
        echo 'android.ndk = 25.1.8937393' >> buildozer.spec
        echo 'android.ndk_api = 21' >> buildozer.spec
        echo 'android.accept_sdk_license = True' >> buildozer.spec
        echo 'android.skip_update = True' >> buildozer.spec
        echo "android.sdk_path = ${ANDROID_HOME}" >> buildozer.spec
        echo 'android.gradle_dependencies = androidx.core:core:1.6.0' >> buildozer.spec
        echo 'android.enable_androidx = True' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'android.presplash_color = #FFFFFF' >> buildozer.spec
        echo 'android.orientation = portrait' >> buildozer.spec
        echo 'p4a.local_recipes = ./recipes' >> buildozer.spec
        echo '' >> buildozer.spec
        echo '[buildozer]' >> buildozer.spec
        echo 'log_level = 2' >> buildozer.spec
        echo 'warn_on_root = 1' >> buildozer.spec

    - name: Build APK
      run: |
        export PATH=${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:$PATH
        export ANDROID_NDK_HOME=${ANDROID_HOME}/ndk/25.1.8937393
        
        echo "=== Environment Verification ==="
        echo "ANDROID_HOME: ${ANDROID_HOME}"
        echo "ANDROID_NDK_HOME: ${ANDROID_NDK_HOME}"
        echo "PATH: $PATH"
        echo "Python version: $(python3 --version)"
        echo "Java version: $(java -version 2>&1)"
        echo "SDK directory contents:"
        ls -R ${ANDROID_HOME}
        
        buildozer android clean
        buildozer android debug -v

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: bin/*.apk
