name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer Cython==0.29.33
        sudo apt-get update
        sudo apt-get install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        sudo apt-get install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
        sudo apt-get install -y android-tools-adb android-tools-fastboot
    
    - name: Setup Android SDK and Build Tools
      run: |
        # Set up Android SDK
        ANDROID_SDK_ROOT="/usr/local/lib/android/sdk"
        BUILD_TOOLS_VERSION="33.0.0"
        
        # Create buildozer directory structure
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/{tools,platforms,platform-tools,build-tools/${BUILD_TOOLS_VERSION}}
        
        # Download SDK tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        
        # Move tools to correct location
        mv cmdline-tools $HOME/.buildozer/android/platform/android-sdk/
        mv $HOME/.buildozer/android/platform/android-sdk/cmdline-tools $HOME/.buildozer/android/platform/android-sdk/tools
        
        # Copy existing SDK components
        sudo cp -r ${ANDROID_SDK_ROOT}/build-tools/${BUILD_TOOLS_VERSION}/* $HOME/.buildozer/android/platform/android-sdk/build-tools/${BUILD_TOOLS_VERSION}/
        sudo cp -r ${ANDROID_SDK_ROOT}/platforms/* $HOME/.buildozer/android/platform/android-sdk/platforms/
        sudo cp -r ${ANDROID_SDK_ROOT}/platform-tools/* $HOME/.buildozer/android/platform/android-sdk/platform-tools/
        
        # Create tools/bin directory and copy sdkmanager
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
        sudo cp ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager $HOME/.buildozer/android/platform/android-sdk/tools/bin/
        
        # Set permissions
        sudo chown -R $USER:$USER $HOME/.buildozer
        
        # Make sdkmanager executable
        chmod +x $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
        
        # Set environment variables
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        export PATH=$PATH:$ANDROID_HOME/tools/bin
        
        # Verify installations
        ls -la $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
        ls -la $HOME/.buildozer/android/platform/android-sdk/build-tools/${BUILD_TOOLS_VERSION}/aidl
    
    - name: Set up buildozer
      run: |
        echo '[app]' > buildozer.spec
        echo 'title = Yoga Timer' >> buildozer.spec
        echo 'package.name = yogatimer' >> buildozer.spec
        echo 'package.domain = org.example' >> buildozer.spec
        echo 'source.dir = .' >> buildozer.spec
        echo 'source.include_exts = py,wav' >> buildozer.spec
        echo 'version = 0.1' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'requirements = python3,kivy,plyer,android,Cython==0.29.33' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE' >> buildozer.spec
        echo 'p4a.bootstrap = sdl2' >> buildozer.spec
        echo 'android.archs = arm64-v8a' >> buildozer.spec
        echo 'android.api = 33' >> buildozer.spec
        echo 'android.minapi = 21' >> buildozer.spec
        echo 'android.ndk = 25b' >> buildozer.spec
        echo 'android.accept_sdk_license = True' >> buildozer.spec
        echo '' >> buildozer.spec
        echo 'android.presplash_color = #FFFFFF' >> buildozer.spec
        echo 'android.orientation = portrait' >> buildozer.spec
        echo '' >> buildozer.spec
        echo '[buildozer]' >> buildozer.spec
        echo 'log_level = 2' >> buildozer.spec
        echo 'warn_on_root = 1' >> buildozer.spec
        echo "android.sdk_path = $HOME/.buildozer/android/platform/android-sdk" >> buildozer.spec
    
    - name: Build with Buildozer
      env:
        ANDROID_HOME: $HOME/.buildozer/android/platform/android-sdk
        PATH: $PATH:$HOME/.buildozer/android/platform/android-sdk/tools/bin
      run: |
        buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: bin/*.apk
